# syntax=docker/dockerfile:1
FROM golang:alpine

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app
COPY shared/ shared/
COPY services/dispatch-service/ services/dispatch-service/

WORKDIR /app/services/dispatch-service

ENV GOWORK=off
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOFLAGS="-mod=mod"

RUN go mod download
RUN go build -o /service .

EXPOSE 8083
CMD ["/service"]