FROM golang:1.26-alpine

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app
COPY shared/ shared/
COPY services/payment-service/ services/payment-service/

WORKDIR /app/services/payment-service

ENV GOWORK=off
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOFLAGS="-mod=mod"

RUN go mod download
RUN GOMAXPROCS=1 go build -p 1 -o /service .

EXPOSE 8084
CMD ["/service"]