FROM golang:1.26-alpine

RUN apk update && apk add --no-cache ca-certificates tzdata

WORKDIR /app
COPY shared/ shared/
COPY services/api-gateway/ services/api-gateway/

WORKDIR /app/services/api-gateway

ENV GOWORK=off
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOFLAGS="-mod=mod"

RUN go mod download
RUN GOMAXPROCS=1 go build -p 1 -o /gateway .

EXPOSE 8001:8001
CMD ["/gateway"]