# syntax=docker/dockerfile:1
FROM golang:alpine

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app
COPY shared/ shared/
COPY services/api-gateway/ services/api-gateway/

WORKDIR /app/services/api-gateway

ENV GOWORK=off
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOFLAGS="-mod=mod"

RUN go mod download
RUN GOMAXPROCS=1 go build -p 1 -o /gateway .

EXPOSE 8001
CMD ["/gateway"]