FROM golang:1.22-alpine AS builder
WORKDIR /build
COPY ../../shared /build/shared
COPY . /build/service
WORKDIR /build/service
RUN go mod download && CGO_ENABLED=0 GOOS=linux go build -o /app/service .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/service .
EXPOSE 8001
CMD ["./service"]
