# syntax=docker/dockerfile:1
FROM golang:1.26-alpine

RUN apk update && apk add --no-cache ca-certificates tzdata

WORKDIR /app
COPY shared/ shared/
COPY services/rider-service/ services/rider-service/

WORKDIR /app/services/rider-service

ENV GOWORK=off
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOFLAGS="-mod=mod"

RUN go mod download
RUN GOMAXPROCS=1 go build -p 1 -o /service .

EXPOSE 8086:8086
CMD ["/service"]