FROM golang:1.26-alpine

RUN apk update && apk add --no-cache ca-certificates

WORKDIR /app

COPY shared/ shared/
COPY services/upload-service/ services/upload-service/

WORKDIR /app/services/upload-service
ENV GOWORK=off
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOMEMLIMIT=512MiB
ENV GOGC=50

RUN go mod download
RUN GOMAXPROCS=1 go build -p 1 -ldflags="-s -w" -o /service .

EXPOSE 8087
CMD ["/service"]