FROM golang:1.26-alpine

RUN apk update && apk add --no-cache ca-certificates tzdata

WORKDIR /app
COPY shared/ shared/
COPY services/order-service/ services/order-service/

WORKDIR /app/services/order-service

ENV GOWORK=off
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOFLAGS="-mod=mod"

RUN go mod download
RUN GOMAXPROCS=1 go build -p 1 -o /service .

EXPOSE 8082
CMD ["/service"]